import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Location from 'expo-location';
import { useRouter } from 'expo-router';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, TextInput } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Image } from 'expo-image';

import { IconSymbol } from '@/components/ui/icon-symbol';
import { StyleProfileModal } from '@/components/style-profile-modal';
import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { API_BASE_URL } from '@/config/api';
import { friendlyErrorMessage } from '@/config/api-error';
import { apiFetch } from '@/config/api-fetch';
import { Fonts } from '@/constants/theme';
import { useAuthedPhotoSource } from '@/hooks/use-authed-photo-source';
import { useThemeColor } from '@/hooks/use-theme-color';

type Outfit = {
  top_id: string | null;
  bottom_id: string | null;
  shoes_id: string | null;
  outerwear_id: string | null;
  reasoning: string;
};

const OCCASION_STORAGE_KEY = 'last-occasion';
const STYLE_PROFILE_STORAGE_KEY = 'style-profile';
const CACHED_OUTFIT_KEY = 'cached-outfit';
const CACHED_OUTFIT_DATE_KEY = 'cached-outfit-date';

const TODAY = new Date().toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' });
const getTodayDateString = () => new Date().toISOString().slice(0, 10);

export default function GenerateScreen() {
  const router = useRouter();
  const textColor = useThemeColor({}, 'text');
  const bgColor = useThemeColor({}, 'background');
  const lineColor = useThemeColor({}, 'line');
  const mutedColor = useThemeColor({}, 'muted');
  const accentColor = useThemeColor({}, 'tint');
  const [outfit, setOutfit] = useState<Outfit | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [occasion, setOccasion] = useState('casual');
  const [location, setLocation] = useState('');
  const [locatingUser, setLocatingUser] = useState(true);
  const [occasionLoaded, setOccasionLoaded] = useState(false);
  const [styleProfile, setStyleProfile] = useState('No preference');
  const [styleModalVisible, setStyleModalVisible] = useState(false);
  const [cacheChecked, setCacheChecked] = useState(false);
  const hasAutoGenerated = useRef(false);

  // Guards against ever trusting/caching a malformed response (e.g. an error
  // body that slipped through with a 200 status) as a real outfit.
  const isCompleteOutfit = (data: any): data is Outfit =>
    !!data && typeof data.reasoning === 'string' && (data.top_id || data.bottom_id || data.shoes_id);

  const cacheOutfit = useCallback((data: Outfit) => {
    AsyncStorage.setItem(CACHED_OUTFIT_KEY, JSON.stringify(data));
    AsyncStorage.setItem(CACHED_OUTFIT_DATE_KEY, getTodayDateString());
  }, []);

  useEffect(() => {
    AsyncStorage.getItem(OCCASION_STORAGE_KEY).then((saved) => {
      if (saved) setOccasion(saved);
      setOccasionLoaded(true);
    });
    AsyncStorage.getItem(STYLE_PROFILE_STORAGE_KEY).then((saved) => {
      if (saved) setStyleProfile(saved);
    });
    // Only regenerate once per calendar day — reopening the app later today
    // should show the same outfit, not call Gemini again for a fresh one.
    AsyncStorage.multiGet([CACHED_OUTFIT_KEY, CACHED_OUTFIT_DATE_KEY]).then((entries) => {
      const savedOutfit = entries[0][1];
      const savedDate = entries[1][1];
      if (savedOutfit && savedDate === getTodayDateString()) {
        const parsed = JSON.parse(savedOutfit);
        if (isCompleteOutfit(parsed)) {
          setOutfit(parsed);
          hasAutoGenerated.current = true;
        } else {
          // A bad response got cached earlier (e.g. a stale-session error
          // body) — discard it so we fall through to generating a fresh one.
          AsyncStorage.multiRemove([CACHED_OUTFIT_KEY, CACHED_OUTFIT_DATE_KEY]);
        }
      }
      setCacheChecked(true);
    });
  }, []);

  const handleStyleProfileChange = useCallback((value: string) => {
    setStyleProfile(value);
    AsyncStorage.setItem(STYLE_PROFILE_STORAGE_KEY, value);
  }, []);

  const handleOccasionChange = useCallback((value: string) => {
    setOccasion(value);
    AsyncStorage.setItem(OCCASION_STORAGE_KEY, value);
  }, []);

  useEffect(() => {
    (async () => {
      try {
        const permission = await Location.requestForegroundPermissionsAsync();
        if (!permission.granted) return;

        const position = await Location.getCurrentPositionAsync({});
        const [place] = await Location.reverseGeocodeAsync({
          latitude: position.coords.latitude,
          longitude: position.coords.longitude,
        });
        if (place?.city) setLocation(place.city);
      } catch {
        // Location detection failed — user can type it in manually instead.
      } finally {
        setLocatingUser(false);
      }
    })();
  }, []);

  const fetchOutfit = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const params = new URLSearchParams({ occasion, location: location || 'Chicago' });
      if (styleProfile !== 'No preference') {
        params.set('style_profile', styleProfile);
      }
      const response = await apiFetch(`${API_BASE_URL}/outfit/today?${params}`);
      if (!response.ok) throw new Error(await friendlyErrorMessage(response));
      const data = await response.json();
      if (!isCompleteOutfit(data)) throw new Error('Received an incomplete outfit.');
      setOutfit(data);
      cacheOutfit(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Something went wrong');
    } finally {
      setLoading(false);
    }
  }, [occasion, location, styleProfile, cacheOutfit]);

  // Auto-generate today's outfit once we know the occasion (from storage),
  // have resolved location (or given up trying), AND have checked whether
  // today's outfit was already cached — so opening the app shows an outfit
  // already in progress instead of an empty state, without regenerating a
  // fresh one every single time the screen mounts.
  useEffect(() => {
    if (occasionLoaded && cacheChecked && !locatingUser && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      fetchOutfit();
    }
  }, [occasionLoaded, cacheChecked, locatingUser, fetchOutfit]);

  const [swappingCategory, setSwappingCategory] = useState<string | null>(null);

  const sendCorrection = useCallback(async (correction: string) => {
    setLoading(true);
    setError(null);
    try {
      const response = await apiFetch(`${API_BASE_URL}/outfit/override`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ correction }),
      });
      if (response.status === 409) {
        // Server has no memory of a prior conversation to correct (e.g. it
        // restarted) — fall back to generating a fresh outfit instead of
        // leaving the user stuck on a dead end.
        await fetchOutfit();
        return;
      }
      if (!response.ok) throw new Error(await friendlyErrorMessage(response));
      const data = await response.json();
      if (!isCompleteOutfit(data)) throw new Error('Received an incomplete outfit.');
      setOutfit(data);
      cacheOutfit(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Something went wrong');
    } finally {
      setLoading(false);
    }
  }, [fetchOutfit, cacheOutfit]);

  const showAnother = useCallback(() => sendCorrection('Show me a completely different outfit.'), [sendCorrection]);

  const swapCategory = useCallback(
    async (category: string) => {
      setSwappingCategory(category);
      await sendCorrection(`Swap only the ${category}. Keep everything else exactly the same.`);
      setSwappingCategory(null);
    },
    [sendCorrection]
  );

  const [refineText, setRefineText] = useState('');
  const [refineOpen, setRefineOpen] = useState(false);

  const submitRefineText = useCallback(() => {
    if (!refineText.trim()) return;
    sendCorrection(refineText.trim());
    setRefineText('');
    setRefineOpen(false);
  }, [refineText, sendCorrection]);

  return (
    <ThemedView style={styles.container}>
      <SafeAreaView style={styles.safeArea}>
        <ThemedView style={styles.masthead}>
          <ThemedView style={styles.mastheadRow}>
            <ThemedText style={[styles.eyebrow, { color: mutedColor }]}>{TODAY.toUpperCase()}</ThemedText>
            <ThemedText style={[styles.eyebrow, { color: accentColor }]}>
              {locatingUser ? 'LOCATING…' : (location || 'Chicago').toUpperCase()}
            </ThemedText>
          </ThemedView>
          <ThemedView style={styles.titleRow}>
            <ThemedText style={styles.h1}>Today</ThemedText>
            <Pressable onPress={() => setStyleModalVisible(true)} hitSlop={12}>
              <IconSymbol name="gearshape.fill" size={20} color={mutedColor} />
            </Pressable>
          </ThemedView>
          <ThemedView style={[styles.rule, { backgroundColor: lineColor }]} />
        </ThemedView>

        <ScrollView style={styles.centerGroupScroll} contentContainerStyle={styles.centerGroup}>
          <ThemedView style={styles.fieldWrap}>
            <ThemedText style={[styles.fieldLabel, { color: mutedColor }]}>DRESSING FOR</ThemedText>
            <TextInput
              style={[styles.fieldInput, { color: textColor, borderBottomColor: lineColor }]}
              value={occasion}
              onChangeText={handleOccasionChange}
              onSubmitEditing={fetchOutfit}
              returnKeyType="done"
              placeholder="a casual day, dinner, work…"
              placeholderTextColor={mutedColor}
            />
          </ThemedView>

          {!outfit && !loading && (
            <ThemedView style={styles.plate}>
              <ThemedView style={styles.emptyRow}>
                <ThemedView style={[styles.emptySlot, { borderColor: lineColor }]}>
                  <IconSymbol name="tshirt" size={26} color={mutedColor} style={styles.emptyIcon} />
                </ThemedView>
                <ThemedView style={[styles.emptySlot, { borderColor: lineColor }]}>
                  <IconSymbol name="bag.fill" size={26} color={mutedColor} style={styles.emptyIcon} />
                </ThemedView>
                <ThemedView style={[styles.emptySlot, { borderColor: lineColor }]}>
                  <IconSymbol name="figure.walk" size={26} color={mutedColor} style={styles.emptyIcon} />
                </ThemedView>
              </ThemedView>
              <Pressable style={[styles.button, { backgroundColor: textColor }]} onPress={fetchOutfit}>
                <ThemedText style={[styles.buttonText, { color: bgColor }]}>GET TODAY&apos;S OUTFIT</ThemedText>
              </Pressable>
            </ThemedView>
          )}

          {!outfit && loading && <ActivityIndicator size="large" style={styles.spacing} />}

          {error && (
            <ThemedView style={styles.errorRow}>
              <ThemedText style={{ color: mutedColor }}>{error}</ThemedText>
              <Pressable style={[styles.button, styles.errorButton, { backgroundColor: textColor }]} onPress={fetchOutfit}>
                <ThemedText style={[styles.buttonText, { color: bgColor }]}>RETRY</ThemedText>
              </Pressable>
            </ThemedView>
          )}

          {outfit && (
            <ThemedView style={styles.plate}>
              <ThemedText style={[styles.plateTag, { color: accentColor }]}>
                {swappingCategory
                  ? 'SWAPPING…'
                  : loading
                    ? 'FINDING SOMETHING NEW…'
                    : 'TAP A PIECE TO SWAP IT'}
              </ThemedText>

              <ThemedView style={[styles.emptyRow, loading && !swappingCategory && styles.dimmed]}>
                {outfit.outerwear_id && (
                  <StackGarment
                    itemId={outfit.outerwear_id}
                    lineColor={lineColor}
                    onPress={() => swapCategory('outerwear')}
                    isSwapping={swappingCategory === 'outerwear'}
                    disabled={loading}
                  />
                )}
                <StackGarment
                  itemId={outfit.top_id}
                  lineColor={lineColor}
                  onPress={() => swapCategory('top')}
                  isSwapping={swappingCategory === 'top'}
                  disabled={loading}
                />
                <StackGarment
                  itemId={outfit.bottom_id}
                  lineColor={lineColor}
                  onPress={() => swapCategory('bottom')}
                  isSwapping={swappingCategory === 'bottom'}
                  disabled={loading}
                />
                <StackGarment
                  itemId={outfit.shoes_id}
                  lineColor={lineColor}
                  onPress={() => swapCategory('shoes')}
                  isSwapping={swappingCategory === 'shoes'}
                  disabled={loading}
                />
              </ThemedView>

              <ThemedView style={[styles.rule, styles.plateRule, { backgroundColor: lineColor }]} />

              <ThemedText style={[styles.reasoning, loading && !swappingCategory && styles.dimmed]}>
                {outfit.reasoning}
              </ThemedText>

              {refineOpen ? (
                <TextInput
                  style={[styles.refineInput, { color: textColor, borderBottomColor: lineColor }]}
                  value={refineText}
                  onChangeText={setRefineText}
                  onSubmitEditing={submitRefineText}
                  onBlur={() => !refineText && setRefineOpen(false)}
                  returnKeyType="done"
                  autoFocus
                  editable={!loading}
                  placeholder="e.g. hide a coffee stain, more relaxed…"
                  placeholderTextColor={mutedColor}
                />
              ) : (
                <Pressable onPress={() => setRefineOpen(true)} disabled={loading}>
                  <ThemedText style={[styles.refineLink, { color: mutedColor }]}>+ something specific</ThemedText>
                </Pressable>
              )}

              <ThemedView style={styles.btnRow}>
                <Pressable
                  style={[styles.button, styles.outlineButton, styles.flexButton, { borderColor: textColor }]}
                  onPress={showAnother}
                  disabled={loading}>
                  <ThemedText style={[styles.buttonText, { color: textColor }]}>SHOW ANOTHER</ThemedText>
                </Pressable>
                <Pressable
                  style={[styles.button, styles.flexButton, { backgroundColor: textColor }]}
                  onPress={() => router.push('/explore')}>
                  <ThemedText style={[styles.buttonText, { color: bgColor }]}>WARDROBE</ThemedText>
                </Pressable>
              </ThemedView>
            </ThemedView>
          )}
        </ScrollView>
      </SafeAreaView>

      <StyleProfileModal
        visible={styleModalVisible}
        value={styleProfile}
        onClose={() => setStyleModalVisible(false)}
        onSave={handleStyleProfileChange}
      />
    </ThemedView>
  );
}

function StackGarment({
  itemId,
  lineColor,
  onPress,
  isSwapping,
  disabled,
}: {
  itemId: string | null;
  lineColor: string;
  onPress: () => void;
  isSwapping?: boolean;
  disabled?: boolean;
}) {
  const source = useAuthedPhotoSource(`${API_BASE_URL}/photos/${itemId}`);
  if (!itemId) return null;
  return (
    <Pressable
      onPress={onPress}
      disabled={disabled}
      style={[styles.emptySlot, styles.filledSlot, { borderColor: lineColor }]}>
      {isSwapping ? (
        <ActivityIndicator size="small" />
      ) : (
        <Image source={source} style={styles.stackPhoto} contentFit="cover" />
      )}
    </Pressable>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  masthead: {
    gap: 8,
  },
  mastheadRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  eyebrow: {
    fontFamily: Fonts.mono,
    fontSize: 10.5,
    fontWeight: '600',
    letterSpacing: 1.5,
  },
  h1: {
    fontFamily: Fonts.serif,
    fontSize: 46,
    lineHeight: 50,
    fontWeight: '600',
    letterSpacing: -1,
  },
  rule: {
    height: 1,
    width: '100%',
  },
  centerGroupScroll: {
    flex: 1,
  },
  centerGroup: {
    flexGrow: 1,
    justifyContent: 'center',
    gap: 32,
    paddingVertical: 20,
  },
  fieldWrap: {
    gap: 8,
  },
  fieldLabel: {
    fontFamily: Fonts.mono,
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 2,
  },
  fieldInput: {
    fontFamily: Fonts.serif,
    fontSize: 22,
    paddingVertical: 8,
    borderBottomWidth: 1,
  },
  spacing: {
    marginTop: 24,
  },
  plate: {
    gap: 18,
  },
  plateTag: {
    fontFamily: Fonts.mono,
    fontSize: 10.5,
    fontWeight: '700',
    letterSpacing: 2,
    textAlign: 'center',
  },
  emptyRow: {
    flexDirection: 'column',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'transparent',
  },
  emptySlot: {
    width: '34%',
    aspectRatio: 1,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyIcon: {
    opacity: 0.5,
  },
  filledSlot: {
    overflow: 'hidden',
  },
  dimmed: {
    opacity: 0.4,
  },
  errorRow: {
    alignItems: 'center',
    gap: 12,
  },
  errorButton: {
    alignSelf: 'center',
    paddingHorizontal: 32,
  },
  flexButton: {
    flex: 1,
  },
  stackPhoto: {
    width: '100%',
    height: '100%',
    borderRadius: 14,
  },
  plateRule: {
    marginVertical: 2,
  },
  reasoning: {
    fontFamily: Fonts.serif,
    fontStyle: 'italic',
    fontSize: 17,
    lineHeight: 25,
    textAlign: 'center',
  },
  refineLink: {
    fontFamily: Fonts.mono,
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  refineInput: {
    fontFamily: Fonts.serif,
    fontSize: 16,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: 6,
    borderBottomWidth: 1,
  },
  btnRow: {
    flexDirection: 'row',
    gap: 10,
    backgroundColor: 'transparent',
  },
  button: {
    alignSelf: 'stretch',
    paddingVertical: 16,
    borderRadius: 100,
    alignItems: 'center',
  },
  outlineButton: {
    backgroundColor: 'transparent',
    borderWidth: 1.5,
  },
  buttonText: {
    fontFamily: Fonts.mono,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1.5,
  },
});
